// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKefKdhEpmLuwobmACo0q9GUxmolxVb_s',
    appId: '1:676604351444:android:d0da728007693190d5bc41',
    messagingSenderId: '676604351444',
    projectId: 'avaliapp-e041d',
    storageBucket: 'avaliapp-e041d.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKefKdhEpmLuwobmACo0q9GUxmolxVb_s',
    appId: '1:676604351444:android:d0da728007693190d5bc41',
    messagingSenderId: '676604351444',
    projectId: 'avaliapp-e041d',
    storageBucket: 'avaliapp-e041d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzFTYFYGOzIgv_rCEkVKxIr0nr5off3E0',
    appId: '1:676604351444:ios:84d0c9173fd74ee2d5bc41',
    messagingSenderId: '676604351444',
    projectId: 'avaliapp-e041d',
    storageBucket: 'avaliapp-e041d.appspot.com',
    iosBundleId: 'br.com.avaliapp.coltec.avaliapp',
  );
}
